FROM python:3.9.18-bullseye
WORKDIR /app
ADD . .
RUN apt-get update
RUN apt-get -y install python3-dev default-libmysqlclient-dev build-essential
RUN apt-get -y install nodejs npm
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
  tar -xvzf ta-lib-0.4.0-src.tar.gz && \
  cd ta-lib/ && \
  ./configure --prefix=/usr && \
  make && \
  make install
RUN pip install -r requirements.txt

ENV DATABASE_URL=mysql+pymysql://cb:cryptoBricks123@cb-rds.cw5tnk9dgstt.us-west-2.rds.amazonaws.com:3306/test?charset=utf8mb4
ENV DATABASE_CEX_URL=mysql://cb:cryptoBricks123@52.39.20.198:3306/test?charset=utf8mb4
ENV PYTHONPATH=/app
CMD ["python", "main.py"]